# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment_post',
            options={'verbose_name': 'Коментарии', 'verbose_name_plural': 'Коментарии'},
        ),
        migrations.AddField(
            model_name='comment_post',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment_post',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.1.0.1', verbose_name='ip'),
        ),
        migrations.AddField(
            model_name='comment_post',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='comment_post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 23, 41, 7, 835168), verbose_name='Дата комментария'),
        ),
        migrations.AddField(
            model_name='comment_post',
            name='text',
            field=models.TextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comment_post',
            name='vk_url',
            field=models.URLField(max_length=250, null=True),
        ),
    ]
