# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20171003_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='comment_post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 3, 23, 48, 53, 937501), verbose_name='Дата комментария'),
        ),
    ]
