# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20171004_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='img',
            field=models.ImageField(blank=True, default='/media/img/intro_vOaT9r2.jpg', upload_to='img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 20, 54, 54, 103787), verbose_name='Дата комментария'),
        ),
    ]
