# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20171004_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 21, 11, 1, 948316), verbose_name='Дата комментария'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='text',
            field=models.TextField(default=1, verbose_name='Комментарий'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='vk_url',
            field=models.URLField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
