# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_auto_20171004_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='img',
            field=models.ImageField(blank=True, default='/img/intro_vOaT9r2.jpg', upload_to='img', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 4, 21, 12, 27, 3345), verbose_name='Дата комментария'),
        ),
    ]
