# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:53
from __future__ import unicode_literals

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20171004_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='file',
            field=models.FileField(default=0, upload_to='documents/%Y/%m/%d', validators=[comments.models.validate_file_extension]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 23, 53, 35, 129157), verbose_name='Дата комментария'),
        ),
    ]
