# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 20:58
from __future__ import unicode_literals

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_auto_20171006_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='file',
            field=models.FileField(upload_to='img', validators=[comments.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 6, 23, 58, 51, 168109), verbose_name='Дата комментария'),
        ),
    ]
