# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 21:16
from __future__ import unicode_literals

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0010_auto_20171006_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentpost',
            name='file',
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='img',
            field=models.ImageField(blank=True, default='/img/intro_vOaT9r2.jpg', upload_to='img', validators=[comments.models.validate_file_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 7, 0, 16, 13, 868434), verbose_name='Дата комментария'),
        ),
    ]
