# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 12:56
from __future__ import unicode_literals

import comments.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0011_auto_20171007_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='img',
            field=models.ImageField(blank=True, default='/img/comments/vector-smart-object.png', upload_to='img', validators=[comments.models.validate_file_extension], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 15, 56, 29, 125837), verbose_name='Дата комментария'),
        ),
    ]
