# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0013_auto_20171008_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 8, 16, 4, 21, 688770), verbose_name='Дата комментария'),
        ),
    ]
